
"""Centralized DuckDB table metadata used for query validation."""
from __future__ import annotations

from typing import Mapping


DUCKDB_TABLE_COLUMNS: Mapping[str, tuple[str, ...]] = {
    "candles": (
        "asset_id",
        "coin",
        "timeframe",
        "ts",
        "open",
        "high",
        "low",
        "close",
        "volume",
        "rsi",
        "ema_12",
        "ema_26",
        "macd",
        "macd_signal",
        "macd_hist",
        "bb_middle",
        "bb_upper",
        "bb_lower",
        "willr",
        "atr",
        "atr_14",
        "plus_di_14",
        "minus_di_14",
        "adx",
        "adx_14",
        "cci",
        "cci_14",
        "stoch_k_9",
        "stoch_d_9_6",
        "stoch_rsi_14",
        "ultimate_osc",
        "roc_12",
        "ema_13",
        "bull_power_13",
        "bear_power_13",
        "bull_bear_power_13",
        "highs_lows_14",
        "sma_5",
        "ema_5",
        "sma_10",
        "ema_10",
        "sma_20",
        "ema_20",
        "sma_50",
        "ema_50",
        "sma_100",
        "ema_100",
        "sma_200",
        "ema_200",
        "peak_high_high",
        "peak_high_close",
        "peak_low_low",
        "peak_low_close",
        "ts_int",
    ),
    "divergence": (
        "asset_id",
        "timeframe",
        "start_datetime",
        "end_datetime",
        "entry_datetime",
        "entry_price",
        "previous_peak_datetime",
        "divergence",
        "price_change",
        "rsi_change",
        "strength_score",
    ),
    "indicator_rules": (
        "indicator_key",
        "indicator_name",
        "description",
        "required_columns",
        "timeframes",
    ),
    "indicator_signal_summary": (
        "asset_id",
        "symbol",
        "timeframe",
        "evaluated_at",
        "buy_count",
        "sell_count",
        "neutral_count",
        "unknown_count",
        "total_indicators",
        "overall_signal",
        "dominant_ratio",
    ),
    "indicator_signals": (
        "asset_id",
        "symbol",
        "timeframe",
        "indicator_key",
        "indicator_name",
        "indicator_value",
        "signal",
        "reason",
        "evaluated_at",
    ),
    "news_articles": (
        "article_id",
        "guid",
        "source",
        "title",
        "body",
        "excerpt",
        "url",
        "published_at",
        "created_at",
        "updated_at",
        "author",
        "categories",
        "category_names",
        "tags",
        "tag_names",
        "sentiment",
        "image_url",
    ),
    "strategies": (
        "strategy_id",
        "indicator_key",
        "name",
        "signal_type",
        "buy_condition",
        "sell_condition",
        "neutral_condition",
        "notes",
        "timeframes",
        "tags",
        "confidence_level",
        "source",
        "created_at",
        "last_updated",
    ),
}
